#ifndef _COMMANDLINE_H_
#define _COMMANDLINE_H_

enum {
	GETOPT_VAL_NC = 257,
	GETOPT_VAL_KEY,
	GETOPT_VAL_CRYPT,
	GETOPT_VAL_MODE,
	GETOPT_VAL_MTU,
	GETOPT_VAL_SNDWND,
	GETOPT_VAL_RCVWND,
	GETOPT_VAL_DATASHARD,
	GETOPT_VAL_PARITYSHARD,
	GETOPT_VAL_DSCP,
	GETOPT_VAL_NOCOMP,
	GETOPT_VAL_ACKNODELAY,
	GETOPT_VAL_NODELAY,
	GETOPT_VAL_INTERVAL,
	GETOPT_VAL_RESEND,
	GETOPT_VAL_SOCKBUF,
	GETOPT_VAL_KEEPALIVE,
	GETOPT_VAL_SYSLOG,
	GETOPT_VAL_HELP,
	GETOPT_VAL_VERSION
};

/** @brief Parses the command line and set the config accordingly */
void parse_commandline(int, char **);

void usage();

#endif                          /* _COMMANDLINE_H_ */
